### ISSUE TITLE
Override text-shadow

### ISSUE THREAD

**Issue by kmlucy** [rpeyron/plugin-button#12]
Is there anyway to override the text-shadow property? From what I can tell, the conf.styles only applies to the `.plugin_button` selector, and there is no way to apply styles to the `.plugin_button_text` selector.

**Comment by rpeyron** [comment]
There is indeed no simple way currently. Not a very elegant solution, but if you have access to dokuwiki's configuration best way is to override with a custom CSS.  Or you may also include in the page `<html><style>.plugin_button_text { text-shadow: none !important; }</style></html>`

If these 'solutions' do not fit your situation, please tell, I may have a look to find why this property was defined here and not in the top-level class, and move there if it does no harm.

**Comment by kmlucy** [comment]
Including the html in the page doesn't work for me, unless I'm doing something wrong. It just shows as text in the page.

Adding the css to my `userstyle.css` does work, but it would definitely be cleaner if it could be applied on a button by button basis.

**Comment by rpeyron** [comment]
Hello, I have changed the CSS to move the text-shadow to the upper-level, allowing a per-button override. I did not detect an unwanted appearance change doing that, but please report if any. The change is not yet released through plugin manager, please update manually and confirm this is working OK for you. Thanks

**Comment by kmlucy** [comment]
I updated to the new version and everything is working perfectly. Thanks for the quick fix!
