### ISSUE TITLE
Incompatibility with new version: Release rc-2020-06-09 “Hogfather” RC3

### ISSUE THREAD

**Issue by Ale-BB** [rpeyron/plugin-button#13]
Hello,
not sure if I'm the only one experiencing a problem after the latest DokuWiki **Release rc-2020-06-09 “Hogfather” RC3**, but the plugin doesn't work well anymore for me.
It works well right after the update, showing the buttons I created.
If I edit the page and save it, or even if I press Cancel, I get an error that replaces the page, without letting me see it at all.
If I disable the plugin from the plugin manager, the page comes back (no data loss), showing me the syntax of the buttons instead of their graphic version.

**Actually I'm running DokuWiki on a XAMPP server with php 7.4.3**

Here's the error I get:
`Fatal error: Uncaught Error: Call to undefined function Doku_Handler_Parse_Media() in C:\xampp\htdocs\bananawiki\lib\plugins\button\syntax.php:218 Stack trace: #0 C:\xampp\htdocs\bananawiki\inc\parser\renderer.php(117): syntax_plugin_button->render('xhtml', Object(Doku_Renderer_xhtml), Array) #1 C:\xampp\htdocs\bananawiki\inc\parserutils.php(673): Doku_Renderer->plugin('button', Array, 1, '[[{icons:dokuwi...') #2 C:\xampp\htdocs\bananawiki\inc\parserutils.php(142): p_render('xhtml', Array, NULL) #3 C:\xampp\htdocs\bananawiki\inc\parserutils.php(89): p_cached_output('C:/xampp/htdocs...', 'xhtml', 'guide:bananawik...') #4 C:\xampp\htdocs\bananawiki\inc\html.php(305): p_wiki_xhtml('guide:bananawik...', 0, true, '') #5 C:\xampp\htdocs\bananawiki\inc\Action\Show.php(33): html_show() #6 C:\xampp\htdocs\bananawiki\inc\template.php(99): dokuwiki\Action\Show->tplContent() #7 [internal function]: tpl_content_core('show') #8 C:\xampp\htdocs\bananawiki\inc\Extension\Event.php(129): call_user_func_array('tpl_content_cor...', Array) #9 in C:\xampp\htdocs\bananawiki\lib\plugins\button\syntax.php on line 218
`

Thanks!

**Comment by rpeyron** [comment]
Hello,

I have updated and tested with my DokuWiki installation (PHP7.3) and with a fresh installation of Hogfather rc3  (with the bundled MicroApache PHP5.6) and the plugin seems to be working fine in both cases. 

As the incriminated function in the error is Doku_Handler_Parse_Media, could you please check if it is OK with your installation?  It should be located in the file inc/parser/handler.php at line 1069.  Could you test a fresh install with your PHP version to test if it is specific to the version you use?

PS: the error occurs only when editing the page because the data are in the cache before. It is only when editing the page that the button syntax is parsed and the Doku_Handler_Parse_Media function is called to get the media URL.

Thanks for your help

**Comment by mais1e** [comment]
Hello, I'm having the same issue with essentially the same error log. 

`Fatal error: Uncaught Error: Call to undefined function Doku_Handler_Parse_Media() in /home/customer/www/address/public_html/lib/plugins/button/syntax.php:228 Stack trace: #0 /home/customer/www/address/public_html/inc/parser/renderer.php(117): syntax_plugin_button->render('xhtml', Object(Doku_Renderer_xhtml), Array) #1 /home/customer/www/address/public_html/inc/parserutils.php(673): Doku_Renderer->plugin('button', Array, 1, '[[{:m365:m365_i...') #2 /home/customer/www/address/public_html/inc/parserutils.php(142): p_render('xhtml', Array, NULL) #3 /home/customer/www/address/public_html/inc/parserutils.php(89): p_cached_output('/home/u1449-xhe...', 'xhtml', 'm365:m365') #4 /home/customer/www/address/public_html/inc/html.php(305): p_wiki_xhtml('m365:m365', 0, true, '') #5 /home/customer/www/address/public_html/inc/Action/Show.php(33): html_show() #6 /home/customer/www/address/public_html/inc/template.php(99): dokuwiki\Action\Show->tplContent() #7 [interna in /home/customer/www/address/public_html/lib/plugins/button/syntax.php on line 228`

I haven't yet tested a fresh install, but the thing that seems to fix it every time the error comes up now is to use the touch command on conf/local.php as outlined here - https://www.dokuwiki.org/caching 

Will do another upgrade following the instructions here - https://www.dokuwiki.org/install:upgrade - and report back!

I'm running Dokuwiki on a centOS webserver running PHP 7.3.20

**Comment by mais1e** [comment]
Did a fresh install of the latest stable again and still having the same issues. And can still magically fix it by using 'touch conf/local.php'. 

Also I'm a ding dong, I'm running Dokuwiki on a _**Fedora**_ webserver with PHP 7.3.20

**Comment by rpeyron** [comment]
Ok I managed to reproduce the issue this time and I think I understood what is wrong: this plugin was written without a good knowledge of Dokuwiki and the cache management does not follow Dokuwiki's rules. It seems that a function that I was using in the render part (after the cache) is located in a source file that is no more included in this part when cache exists. The touch command clears the cache and therefore the file was loaded OK, but should not work on the second call... 

As this implies some work to fix nicely this issue by refactoring the render / handle, and as this will cause breaking changes in cache contents for working installations, I will in first place provide a simple fix to include the missing file.  And then work to a more suitable solution (only if I find a way to force cache clearing while upgrading the plugin).

**Comment by mais1e** [comment]
Hey thanks so much! The update pushed out today has made everything work again, really appreciate that!

Good luck with the further updates :)
