### ISSUE TITLE
Center Image in a button ?

### ISSUE THREAD

**Issue by Alex-Goaga** [rpeyron/plugin-button#15]
Hello,
Based on the docs we can have picture and text using the syntax : [[{namespace:image|extra css}wiki page|**Title** of the link]]
I tried multiple ideas of tinkering a button with just an centered image and didn't manage to find a functional idea such as : 

[[{ :herepic.png?300| width:45%;background-color: #FEFEFE;}heresthelink|]] [[{ :herepic.png?300| width:45%;background-color: #FEFEFE;}heresthelink|]]

2 big buttons on the same row , but the images are both on the left side of the button.

Using the latest "button Plugin" on the latest version of doku wiki (hogfather)

**Comment by rpeyron** [comment]
Hello, it should be possible by putting the image in the title of the link, and with ?nolink extension to avoid a <a> element aroung the image that will put the image outside the button. Please try " [[{|width:45%;background-color: #FEFEFE;}heresthelink|{{:herepic.png?nolink&300}}]] "

**Comment by Alex-Goaga** [comment]
let me tell you that you're a genius and you should get a raise for your work. Works like a charm ! thank you
