### ISSUE TITLE
Images don't work

### ISSUE THREAD

**Issue by ross41** [rpeyron/plugin-button#17]
Greetings.

I don't know why, but no matter what I do, images do not show on the buttons. I've tried different sizes and extensions, different formatting, even. But so far no luck. Wiki's media-manager otherwise works perfectly, all of my images are displayed properly.

I doubt any of my plugins interfere with this one. Cache was flushed just in case, as were the cookies.

My version is Hogfather (stable release, naturally). The template is Vector.

**Comment by rpeyron** [comment]
Hello, the plugin has been tested with Hogfather and I just tested with Vector template and everything seems to be working as it should. Could you provide me some more information to be able to help you ?  (for instance the wiki code that is not working, and the wiki code of a working image from media-manager)

**Comment by ross41** [comment]
I am sincerely sorry, it is I to blame for this ordeal.

I have been using Vector for years now, and have heavily customized it to suit my needs. One of the hacks I applied to the template's user.js file was making images scaled to the width of a body, so they wouldn't exceed page's visible region. Obviously, it messed up your plugin.

Here's the hack. It's not my creation, of course; it came from template creator. 
```
let vectorstyle = document.createElement('style');
vectorstyle.id = "custom-styles";
document.head.appendChild(vectorstyle);
vectorstyle.innerHTML = "div#bodyContent img, div#bodyContent svg { max-width: 100%; height: auto; object-fit: cover; }";
```

Again, I apologize for disturbing you with this non-existent issue. And thank you for your plugin, it has greatly improved the looks of my Wiki.
