### ISSUE TITLE
Problem using with images

### ISSUE THREAD

**Issue by Anseur01** [rpeyron/plugin-button#18]
Hi, I'm trying to use this plug in as part of making a wiki with Dokuwiki, but I can't seem to get the images to work. I saw that there was one other user in your bug reports, but they were using a different template to me and found a problem in their template that was their cause.

I'm guessing I'm doing something wrong but I've read and re-read your syntax on the plugin page and I can't see what It could be.

Here is what I am putting into the editor for one of the buttons on the page:

`[[{buttons:link.png|width: 12em;}http://passwordreset.microsoftonline.com|Ad Password Reset]]`

Here is the block of code that results in the wiki from this:

`<a href="http://passwordreset.microsoftonline.com"><span class="plugin_button" style="width: 12em;"><span class="plugin_button_image"><img src="/numbers/lib/exe/fetch.php?cache=&amp;media=buttons:link.png" class="media" alt=""></span><span class="plugin_button_text urlextern">Ad Password Reset</span></span></a>`

The image file is in the correct place in the wikis folder structure, and if I inspect the page in Chomre and mouse over the image tag, the image shows up, so I know the path is correct and it has been uploaded into the 'buttons' namespace that I created by uploading the image with 'buttons:'(without quotes) in front of the file name.

On the actual wiki page, the button just looks like a button with the image showing up, with a little globe symbol on it. (Chomes broken image icon I'm guessing?) Screenshot here (https://pasteboard.co/K6rlvnxO.png)

I'm using the 'Mywiki' template with some of my half completed style edits if it matters.

**Comment by Anseur01** [comment]
I have done some more playing around, and I think this is the result of some of the default CSS in the 'mywiki' style. The default style does not show this problem. When using the mywiki style, the computed CSS dimensions of the images is 0x0, this is why they don't show.

Specifically, if I look at the live CSS, and imspect the image tag, the section for this style:

`#content img {
    height: auto;
    max-width: 100%;
    margin-bottom: 15px;
}`

If I disable the 'max-width' attribute, the problem goes away. If I can find where in this styles CSS that is , I can perminantly get rid of it, but I'm concerned that this would probably break something else in the style. 

Is there a way I can some how break out of that style within the confines of your button plugin, so that CSS does not apply to the buttons?


EDIT: I found your style options for the buttons in the general config, and I made one for the default like so:

`default|font-family: "Gotham Book", Arial, sans-serif; max-width: none`

But looking at the styles section in the Chrome inspection window this CSS is being loaded before the CSS from the template, so is being overwritten by the CSS above that appys the problematic max-width. I tried adding !important to the default styling, but this !important css code does not seem to show up on the output.

**Comment by rpeyron** [comment]
Hello, the problem is caused by the use of #content that has a higher priority than the use of CSS classes. Could you try to replace the line 45 of the file button/style.css (https://github.com/rpeyron/plugin-button/blob/master/style.css)  by 

`#content .plugin_button_image img {`

If it works for you, I will add it in the plugin.

As mywiki template seems to override other CSS style like this (see mywiki.css) ; it may be necessary to add more style to have a good display. Please let me know.

**Comment by Anseur01** [comment]
Hi,

With that edit on line 45, this does indeed correct the problem. Thanks very much.

**Comment by rpeyron** [comment]
Thank you for your feedback, I have added it in the plugin.
