### ISSUE TITLE
Request: Add an option to have vertical image/text buttons

### ISSUE THREAD

**Issue by Anseur01** [rpeyron/plugin-button#19]
Hi,

Just a small idea. Add an option via the editor syntax to have the text for a button below the image instead of to it's right. 

I have done some hacking up of the mode myself to achieve this, but it's a little messy in terms of customisation for others users and I did it by changing the code to make all buttons like this, rather than it being an option for each button.

**Comment by rpeyron** [comment]
Hello, have you tried with style `flex-direction: column;display: flex;` ?
`[[{wiki:dokuwiki-128.png?32|width: 15em;flex-direction: column;display: flex;}test2]]`
