### ISSUE TITLE
Undefined array key

### ISSUE THREAD

**Issue by nerun** [rpeyron/plugin-button#22]
My error log:
```
PHP Warning:  Undefined array key "user:nerun:playground" in /wiki/lib/plugins/button/syntax.php on line 83
PHP Warning:  Undefined array key "user:nerun:playground" in /wiki/lib/plugins/button/syntax.php on line 129
PHP Warning:  Undefined array key 1 in /wiki/lib/plugins/button/syntax.php on line 362
PHP Warning:  Undefined array key 1 in /wiki/lib/plugins/button/syntax.php on line 407
```
I have buttons in my start page and in a user:playground.

[My Wiki](https://www.gurpzine.com.br/wiki/doku.php?id=start)

Any idea?

**Comment by rpeyron** [comment]
Hello, could you please try this branch https://github.com/rpeyron/plugin-button/tree/fix-warning to see if the fixes are OK?

**Comment by nerun** [comment]
Tested... Looks less worse...

```
Undefined variable $hash in .../lib/plugins/button/syntax.php on line 395
Undefined variable $hash in .../lib/plugins/button/syntax.php on line 431
Undefined array key "start" in .../lib/plugins/button/syntax.php on line 83
```

**Comment by rpeyron** [comment]
Tried to fix those in the same branch.  Could you please test again? Which PHP version are you using? (looks like yours warns if using undefined variables)

**Comment by nerun** [comment]
PHP 8.1, i will try later, thx.

**Comment by nerun** [comment]
Tested... FIXED ALL WARNINGS. Love you!

You can close when you wish.

**Comment by rpeyron** [comment]
Thanks for your feedback. I have merged the branch and released this new version as an update.
