### ISSUE TITLE
PHP 7.4 compatibility error: Call to undefined function str_contains()

### ISSUE THREAD

**Issue by jnv** [rpeyron/plugin-button#26]
Hi, I understand that PHP 7.4 is recently unsupported, unfortunately we are stuck on this outdated version due to lack of compatibility with PHP 8.0 in other plugins.

When I updated the plugin recently, all pages where the buttons are used started to fail with the error: `Call to undefined function str_contains()` since `str_contains` is available only in PHP 8.0.

I was able to easily fix the issue by polyfilling the missing function with the following code in `syntax.php`:

```php
if (!function_exists('str_contains')) {
    function str_contains(string $haystack, string $needle): bool
    {
        return '' === $needle || false !== strpos($haystack, $needle);
    }
}
```

So I wanted to ask if you'd be willing to accept this fix, I will be happy to send you a PR.

**Comment by rpeyron** [comment]
Hello, yes, this would be much appreciated. I guess this may also be the reason of #25 that I was unable to understand.

**Comment by rpeyron** [comment]
Merged, thanks!
