### ISSUE TITLE
Plugin fails after nov 2022 update

### ISSUE THREAD

**Issue by MatthijsBerlicum** [rpeyron/plugin-button#27]
Environment:
  - PHP Version 7.4.30

Observed:
 - Wiki-page with included button did not change.
 - After the plugin update an empty page is shown.

Expected:
 - The plugin update should not impact a wiki-page.

Workaround:
  - Disable the plugin-button.

**Comment by rpeyron** [comment]
Should be fixed (thanks to #26) ; can you try the update?

**Comment by MatthijsBerlicum** [comment]
The update passes the test case I checked. Thanks!

Test case:
- Simple support page button:  [[{|width:1em;color:green}Support]]
