### ISSUE TITLE
Buttons in the same page target only the 1st link

### ISSUE THREAD

**Issue by nerun** [rpeyron/plugin-button#30]
After commit d52dfe34b7804d1decf1b7a41f4719b98bd877a9, if i have 2 or more buttons at the same page, ALL the buttons target to the same link, generally the 1st one.

Example: [GURPZine Wiki](https://www.gurpzine.com.br/dokuwiki/doku.php?id=start).

**Comment by rpeyron** [comment]
Ups, sorry; would you be able to try this fix? https://github.com/rpeyron/plugin-button/tree/deprecated-resolver

**Comment by nerun** [comment]
Tested, not working. Nothing changed.

**Comment by rpeyron** [comment]
Ok, I reverted the changes. It seems that I don't understand how the new function works so will keep the deprecated one.
