### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by nerun** [rpeyron/plugin-button#32]
* PHP 8.1
* DokuWiki 2023-04-04a "Jack Jackrum"
* Button plugin 2023-05-29

```
resolve_pageid() is deprecated. It was called from syntax_plugin_button::dokuwiki_get_link() in /lib/plugins/button/syntax.php:312 dokuwiki\File\PageResolver should be used instead!

resolve_pageid() is deprecated. It was called from syntax_plugin_button::internallink() in /lib/plugins/button/syntax.php:359 dokuwiki\File\PageResolver should be used instead!

resolve_mediaid() is deprecated. It was called from syntax_plugin_button::internalmedia() in /lib/plugins/button/syntax.php:423 dokuwiki\File\MediaResolver should be used instead!
```

I don't know how to fix this, but i know that, to fix resolve_pageid() you should add `use dokuwiki\File\PageResolver;` to the top of the `syntax.php` script and adapt this structure: `$resolveid = (new PageResolver($ID))->resolveId($resolveid);`. But i don't know what to do with `$exists` variable.

**Comment by nerun** [comment]
I thin this file fix these deprecations. At least it's working here. [syntax.php.zip](https://github.com/rpeyron/plugin-button/files/12372087/syntax.php.zip)

I made a diff:
![diff](https://github.com/rpeyron/plugin-button/assets/3987342/26f40c23-de9a-4582-96de-026eb60af37d)

**Comment by nerun** [comment]
Not working 100%:
```
PHP Warning:  Undefined variable $exists in .../lib/plugins/button/syntax.php on line 315
PHP Warning:  Undefined variable $exists in .../lib/plugins/button/syntax.php on line 320
PHP Warning:  Undefined variable $exists in .../lib/plugins/button/syntax.php on line 365
PHP Warning:  Undefined variable $exists in .../lib/plugins/button/syntax.php on line 448
```
I have no idea what to do with `$exists`.

**Comment by rpeyron** [comment]
Hello @nerun, thanks, that looks familiar with what I attempted in https://github.com/rpeyron/plugin-button/commit/d52dfe34b7804d1decf1b7a41f4719b98bd877a9 but you encountered the error #30 so I reverted the changes. Do you confirm you haven't the issue #30 with your changes?  I see I may have mixed $id and $ID...

**Comment by nerun** [comment]
I forgot that! I will verify.
