### ISSUE TITLE
Section reference with number sign changes to underscore

### ISSUE THREAD

**Issue by babudro** [rpeyron/plugin-button#5]
Hi.

When I create a button linking to a section within a page the hash/number/pound sign (#) gets changed into an underscore.

If I put [[mypage#mysection]] (i.e., without using the Button plug-in) everything works fine.

If I put [[{}mypage#mysection]] and Save (without Reviewing) then it appears properly at first, but if I refresh the page or come back to it, the link is changed to [[{}mypage_mysection]].

If I Review the page before clicking Save, then it shows properly during Review but immediately after saving shows up incorrectly, with the number sign changed into an underscore.

Since it works as expected without using this plug-in, I'm thinking it must be something that this plug-in is doing to change the link.  Any thoughts on this?

I am using Dokuwiki release 2017-02-19e.

Thank you.

**Comment by rpeyron** [comment]
Thanks for reporting. I guess you are using the move plugin as it was a bug in the section handling page moves that did not take care of sections (and it seems it edits the page at the first display even if the page is not moved). This is now fixed, you may want to upgrade to the last version of the plugin.
