### ISSUE TITLE
Undefined constant DOKU_LEXER_ENTRY

### ISSUE THREAD

**Issue by Ciirdan** [rpeyron/plugin-button#7]
There is a warning on PHP 7.2 :
`PHP Warning:  Use of undefined constant DOKU_LEXER_ENTRY - assumed 'DOKU_LEXER_ENTRY' (this will throw an Error in a future version of PHP) in /lib/plugins/button/syntax.php on line 172`

**Comment by rpeyron** [comment]
Fixed, thanks for reporting.
