### ISSUE TITLE
Unable to use height css parameter

### ISSUE THREAD

**Issue by mammuthus** [rpeyron/plugin-button#8]
Using `[[{icons:mobile-phone-2.png|height:5px}Page|Button title]]`
with big picture gives me something like that:
![image](https://user-images.githubusercontent.com/1700286/60485661-6258c600-9ca6-11e9-86dc-a0cfbb47b909.png)
Very big button. I need to limit height of the picture, how can I do that?

**Comment by rpeyron** [comment]
Easiest way is to reduce your big picture file to the height you want. 
A little explaination why it is not possible directlty through the button plugin : the style included in the button is added to the span of the button, and not to the image itself. That is why is won't reduce image height.
If the solution of reducing the image file does not fit you, you may add custom CSS to your site, using the plugin_button_image class to select the img tag you want (in conf/userstyle.css for instance)
