### ISSUE TITLE
DOKU_LEXER_Entry

### ISSUE THREAD

**Issue by erhapp** [rpeyron/plugin-button#9]
Hello

My DokuWiki installation started showing the following error message: "Warning: Use of undefined constant DOKU_LEXER_ENTRY - assumed 'DOKU_LEXER_ENTRY' (this will throw an Error in a future version of PHP) in /***/dokuwiki/lib/plugins/button/syntax.php on line 172"

Is there anything I can do about this error?

kind regards

Erik

**Comment by rpeyron** [comment]
Hello,
This should be fixed now. Could you please check if it is OK ? (my wiki installation did not report this message). I have not yet published the change in the plugin registry so you will need to trigger manually the plugin reinstallation.
Thanks for reporting
Remi

**Comment by erhapp** [comment]
Hello
I updated the plugin. Everything seems to be working fine. No more error messages. Thank you very much for solving this issue.
kind regards
Erik
